title: Ecoflow Docs
email: your-email@example.com
description: Documentation for Ecoflow integration
baseurl: "" # Leave empty for root
url: "https://6752f6553fc28500086e2942--ecoflow-docs.netlify.app"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - _site
  - _includes